version: "3"
services:
  pg:
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    restart: always
    image: olive-branch/geodyssey
    ports:
      - 8080:80
    depends_on:
      - pg
    environment:
      PGHOST: pg
      PGUSER: postgres
      PGPASSWORD: postgres
